version: '3.8'

services:
  nginx:
    image: nginx:1.25-alpine
    container_name: django_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./media:/var/www/media:rw
      - ./static:/var/www/static:rw
    depends_on:
      - django

  django:
    build: .
    container_name: django_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app:rw
    expose:
      - "8000"
    env_file:
      - .env
    depends_on:
      - redis
      - celery_worker
      - celery_beat

  redis:
    image: redis:7-alpine
    container_name: redis_broker
    expose:
      - "6379"

  celery_worker:
    build: .
    container_name: django_celery_worker
    command: celery -A your_project_name worker --loglevel=info
    volumes:
      - .:/usr/src/app:rw
    env_file:
      - .env
    depends_on:
      - redis

  celery_beat:
    build: .
    container_name: django_celery_beat
    command: celery -A your_project_name beat --loglevel=info
    volumes:
      - .:/usr/src/app:rw
    env_file:
      - .env
    depends_on:
      - redis

volumes:
  media:
  static:
